import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';
import { theme } from '@/styles/theme';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import type { Metadata } from "next";
import '../styles/globals.css'
import { Notifications } from '@mantine/notifications';
import AuthProvider from '@/providers/authProvider';

export const metadata: Metadata = {
  title: "Omega Screen | Gestor",
  description: "Internal management system generated by Omega Screen",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <head>
        <ColorSchemeScript defaultColorScheme='auto' />
      </head>
      <body>
        <MantineProvider theme={theme} defaultColorScheme='auto'>
          <Notifications />
          <AuthProvider>
            {children}
          </AuthProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
