export const productColorOptions = [
  { label: 'incolor', value: 'transparent' },
  { label: 'amarelo', value: '#FFFF09' },
  { label: 'amarelo canário', value: '#FCDE13' },
  { label: 'amarelo fluor', value: '#E8FF18' },
  { label: 'amarelo ouro', value: '#FFA903' },
  { label: 'azul', value: '#099CFF' },
  { label: 'azul anil', value: '#011AAC' },
  { label: 'azul ciano', value: '#3CC4FE' },
  { label: 'azul céu', value: '#67C2FE' },
  { label: 'azul fluor', value: '#00B5FF' },
  { label: 'azul marinho', value: '#080838' },
  { label: 'azul royal', value: '#0063FF' },
  { label: 'azul turquesa', value: '#01F5E7' },
  { label: 'azul ultramar', value: '#1F32C4' },
  { label: 'branco', value: '#FFFFFF' },
  { label: 'castanho', value: '#BA8C4E' },
  { label: 'ciano', value: '#00BDE3' },
  { label: 'cinza', value: '#848484' },
  { label: 'extra brilho preto', value: '#000000' },
  { label: 'laranja', value: '#F06418' },
  { label: 'laranja fluor', value: '#F94E10' },
  { label: 'lavanda', value: '#9380B4' },
  { label: 'lilás', value: '#B381B3' },
  { label: 'magenta', value: '#F01879' },
  { label: 'pink', value: '#F018E8' },
  { label: 'preto', value: '#1F1F1F' },
  { label: 'prata', value: '#B2B2B2' },
  { label: 'roxo', value: '#842885' },
  { label: 'rosa', value: '#D36285' },
  { label: 'rosa fluor', value: '#F414D2' },
  { label: 'verde', value: '#2BDD66' },
  { label: 'verde amazonas', value: '#006127' },
  { label: 'verde bandeira', value: '#006400' },
  { label: 'verde fluor', value: '#3CFF18' },
  { label: 'verde limão', value: '#6BD731' },
  { label: 'vermelho fluor', value: '#C91A25' },
  { label: 'vermelho vivo', value: '#F21616' },
  { label: 'violeta', value: '#7B2EDA' },
  { label: 'violeta fluor', value: '#84099C' },
  { label: 'ouro', value: '#FFBA38' },
];
